### ISSUE TITLE
Publish to AUR

### ISSUE THREAD

**Issue by saidsay-so** [MusiKid/fancy#8]

**Comment by BachoSeven** [comment]
I might do a package for the AUR in like a week(currently got too little internet to download `rust` and test lol), should be easy since you have a makefile which handles flags and whatnot.

**Comment by saidsay-so** [comment]
No problem!
I already created a [PKGBUILD](https://github.com/MusiKid/fancy/blob/develop/PKGBUILD), so you don't really need to work a lot.
Thanks for the help!

**Comment by BachoSeven** [comment]
Perfect, here it is if you want to include it in the README: 
https://aur.archlinux.org/packages/fancy

btw, I removed the `clean()` function since it's not a thing in PKGBUILDs. `makepkg` already has its own `-C` flag, and the package shouldn't really be leaving any file out of place anyways, they should all be inside the build directory.

**Comment by saidsay-so** [comment]
Thank you!
I will add it to the README.
